parameters:
#    demo_tutorial.example.class: Demo\TutorialBundle\Example

services:
#    demo_tutorial.example:
#        class: %demo_tutorial.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
